select MEMBER_ID,MEMBER_NAME,GENDER,DATE_FORMAT(DATE_OF_BIRTH,"%Y-%m-%d") 
from MEMBER_PROFILE 
where GENDER = 'W' && TLNO is not null && MONTH(DATE_OF_BIRTH) = '3';


-- 배운것
DATE_FORMAT(DATE_OF_BIRTH,"%Y-%m-%d")
MONTH(DATE_OF_BIRTH) = '3'
TLNO is not null